# Generated by Django 6.0.6 on 2026-07-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('Kannada_mark', models.IntegerField()),
                ('English_mark', models.IntegerField()),
                ('Hindi_mark', models.IntegerField()),
                ('Maths_mark', models.IntegerField()),
            ],
        ),
    ]
