# Generated by Django 6.0.6 on 2026-07-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradetrack',
            name='average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gradetrack',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='gradetrack',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
