# Generated by Django 6.0.6 on 2026-07-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradeapp', '0002_gradetrack_average_gradetrack_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradetrack',
            name='average',
        ),
        migrations.RemoveField(
            model_name='gradetrack',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='gradetrack',
            name='status',
        ),
    ]
